name: Build and Release

on:
  push:
    branches: [ "main" ]
    paths:
      - 'assets/**'
      - 'sections/**'
      - 'main.tex'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add contributor (if from merged PR)
        run: |
          # Get the merge commit message to extract PR info
          COMMIT_MSG=$(git log -1 --pretty=%B)
          
          # Check if this is a merge commit from a PR
          if echo "$COMMIT_MSG" | grep -q "Merge pull request"; then
            # Extract PR number from merge commit
            PR_NUM=$(echo "$COMMIT_MSG" | grep -o "#[0-9]\+" | head -1 | sed 's/#//')
            
            if [ ! -z "$PR_NUM" ]; then
              # Get PR details using GitHub API
              PR_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUM")
              
              USER=$(echo "$PR_DATA" | jq -r '.user.login')
              TITLE=$(echo "$PR_DATA" | jq -r '.title')
              PR_URL=$(echo "$PR_DATA" | jq -r '.html_url')
              DATE=$(date +"%d/%m/%y")
              
              echo "Adding contributor: @$USER"
              
              # Add contributor to tex file
              echo "" >> contributors.tex
              echo "\\subsection*{@$USER - $DATE}" >> contributors.tex
                echo "$TITLE" >> contributors.tex
                echo "" >> contributors.tex
                echo "" >> contributors.tex
                echo "\\hfill\\url{$PR_URL}" >> contributors.tex
              
              # Commit and push (this will bypass branch protection due to admin token)
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add contributors.tex
              git commit -m "Add contributor: @$USER"
              
              git push
            fi
          fi
      - name: Update version.tex
        run: |
          echo "\\newcommand{\\version}{v0.1.${{ github.run_number }}}" > version.tex
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.tex
          git commit -m "Update version to v${{ github.run_number }}"
          git push

      - name: Download pre-built PDF
        uses: actions/download-artifact@v4
        with:
          name: built-pdf
          path: .
        continue-on-error: true

      - name: Build LaTeX (fallback if no pre-built PDF)
        if: ${{ !hashFiles('main.pdf') }}
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}