name: Build and Release

on:
  push:
    branches: [ "main" ]
    paths:
      - 'assets/**'
      - 'sections/**'
      - 'main.tex'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download pre-built PDF
        uses: actions/download-artifact@v4
        with:
          name: built-pdf
          path: .
        continue-on-error: true

      - name: Build LaTeX (fallback if no pre-built PDF)
        if: ${{ !hashFiles('main.pdf') }}
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
