name: Adds contribution (Preview)

on:
    pull_request:
        branches: [ "main" ]
        types: [opened, synchronize, reopened]

    workflow_dispatch:

jobs:
    preview:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Preview contributor addition
              if: github.event_name == 'pull_request'
              run: |
                  DATE=$(date +"%d/%m/%y")
                  USER="${{ github.event.pull_request.user.login }}"
                  DESCRIPTION="${{ github.event.pull_request.title }}"
                  LINK="${{ github.event.pull_request.html_url }}"
                  echo "When this PR is merged, the following will be added to contributors.tex:"
                  echo ""
                  echo "\\subsection*{@$USER - $DATE}"
                  echo "$DESCRIPTION"
                  echo "\\url{$LINK}"
