name: Adds contribution (Preview)

on:
    pull_request:
        branches: [ "main" ]
        types: [opened, synchronize, reopened]

    workflow_dispatch:

jobs:
    preview:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'

        steps:
            - uses: actions/checkout@v4
            
            - name: Preview contributor addition
              run: |
                  DATE=$(date +"%d/%m/%y")
                  USER="${{ github.event.pull_request.user.login }}"
                  DESCRIPTION="${{ github.event.pull_request.title }}"
                  LINK="${{ github.event.pull_request.html_url }}"
                  echo "When this PR is merged, the following will be added to contributors.tex:"
                  echo ""
                  echo "\\subsection*{@$USER - $DATE}"
                  echo "$DESCRIPTION"
                  echo "\\url{$LINK}"
            

            - name: Build and check for errors
              uses: xu-cheng/latex-action@v4
              with:
                root_file: main.tex
            
            - name: Upload build artifact
              if: success()
              uses: actions/upload-artifact@v4
              with:
                name: built-pdf
                path: main.pdf
                retention-days: 30
