name: Adds contribution (Preview)

on:
    pull_request:
        branches: [ "main" ]
        types: [opened, synchronize, reopened]

    workflow_dispatch:

jobs:
    preview:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'

        steps:
            - uses: actions/checkout@v4
            
            - name: Add contributor entry to PR
              run: |
                  DATE=$(date +"%d/%m/%y")
                  USER="${{ github.event.pull_request.user.login }}"
                  DESCRIPTION="${{ github.event.pull_request.title }}"
                  LINK="${{ github.event.pull_request.html_url }}"
                  
                  # Add contributor to tex file
                  echo "" >> contributors.tex
                  echo "\\subsection*{@$USER - $DATE}" >> contributors.tex
                  echo "$DESCRIPTION" >> contributors.tex
                  echo "\\url{$LINK}" >> contributors.tex
                  
                  # Check if there are changes to commit
                  if ! git diff --quiet contributors.tex; then
                    # Configure git
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"
                    
                    # Commit and push to the PR branch
                    git add contributors.tex
                    git commit -m "Add contributor entry for @$USER"
                    git push origin HEAD:${{ github.event.pull_request.head.ref }}
                  else
                    echo "No changes needed to contributors.tex"
                  fi

            - name: Preview contributor addition
              run: |
                  DATE=$(date +"%d/%m/%y")
                  USER="${{ github.event.pull_request.user.login }}"
                  DESCRIPTION="${{ github.event.pull_request.title }}"
                  LINK="${{ github.event.pull_request.html_url }}"
                  echo "The following has been added to contributors.tex:"
                  echo ""
                  echo "\\subsection*{@$USER - $DATE}"
                  echo "$DESCRIPTION"
                  echo "\\url{$LINK}"
            

            - name: Build and check for errors
              uses: xu-cheng/latex-action@v4
              with:
                root_file: main.tex
            
            - name: Verify compilation success
              run: |
                if [ -f main.log ]; then
                  echo "Checking LaTeX compilation log..."
                  
                  # Check for fatal errors
                  if grep -E "(! |Emergency stop|Fatal error)" main.log; then
                    echo "❌ LaTeX compilation failed with errors!"
                    exit 1
                  fi
                  
                  # Check for undefined references
                  if grep -E "LaTeX Warning: Reference .* undefined" main.log; then
                    echo "❌ Undefined references found!"
                    exit 1
                  fi
                  
                  echo "✅ LaTeX compilation successful!"
                else
                  echo "❌ LaTeX log file not found!"
                  exit 1
                fi
            
            - name: Upload build artifact
              if: success()
              uses: actions/upload-artifact@v4
              with:
                name: built-pdf
                path: main.pdf
                retention-days: 30
