name: Adds contribution (Preview)

on:
    pull_request:
        branches: [ "main" ]
        types: [opened, synchronize, reopened]

    workflow_dispatch:

jobs:
    preview:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'

        steps:
            - uses: actions/checkout@v4
            
            - name: Preview contributor addition
              run: |
                  DATE=$(date +"%d/%m/%y")
                  USER="${{ github.event.pull_request.user.login }}"
                  DESCRIPTION="${{ github.event.pull_request.title }}"
                  LINK="${{ github.event.pull_request.html_url }}"
                  echo "When this PR is merged, the following will be added to contributors.tex:"
                  echo ""
                  echo "\\subsection*{@$USER - $DATE}"
                  echo "$DESCRIPTION"
                  echo "\\url{$LINK}"
            

            - name: Build and check for errors
              uses: xu-cheng/latex-action@v4
              with:
                root_file: main.tex
                args: "-halt-on-error -interaction=nonstopmode"
            
            - name: Verify compilation success
              run: |
                if [ -f main.log ]; then
                  echo "Checking LaTeX compilation log..."
                  
                  # Check for fatal errors
                  if grep -E "(! |Emergency stop|Fatal error)" main.log; then
                    echo "❌ LaTeX compilation failed with errors!"
                    exit 1
                  fi
                  
                  # Check for undefined references
                  if grep -E "LaTeX Warning: Reference .* undefined" main.log; then
                    echo "❌ Undefined references found!"
                    exit 1
                  fi
                  
                  echo "✅ LaTeX compilation successful!"
                else
                  echo "❌ LaTeX log file not found!"
                  exit 1
                fi
            
            - name: Attach to PR
              if: success()
              uses: actions/upload-artifact@v4
              with:
                name: PDF Preview
                path: main.pdf
